package com.command.service.vo;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "bid")
public class BidingDO {

	@Id
	@JsonProperty("id")
	private String id;
	@JsonProperty("productName")
	private String name;
	@JsonProperty("bidderName")
	private String bidderName;
	@JsonProperty("bidAmount")
	private double bidAmount;
	@JsonProperty("bidderEmailId")
	private String bidderEmailId;
	@JsonProperty("bidderPhNo")
	private String bidderPhNo;
	@JsonProperty("bidderAdd")
	private String bidderAdd;
	@JsonProperty("bidderPincode")
	private String bidderPincode;
	@JsonProperty("bidderState")
	private String bidderState;
	
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@DynamoDBHashKey
	@DynamoDBAttribute
	public String getBidderName() {
		return bidderName;
	}
	public void setBidderName(String bidderName) {
		this.bidderName = bidderName;
	}
	@DynamoDBAttribute
	public double getBidAmount() {
		return bidAmount;
	}
	public void setBidAmount(double bidAmount) {
		this.bidAmount = bidAmount;
	}
	@DynamoDBAttribute
	public String getBidderEmailId() {
		return bidderEmailId;
	}
	public void setBidderEmailId(String bidderEmailId) {
		this.bidderEmailId = bidderEmailId;
	}
	@DynamoDBAttribute
	public String getBidderPhNo() {
		return bidderPhNo;
	}
	public void setBidderPhNo(String bidderPhNo) {
		this.bidderPhNo = bidderPhNo;
	}
	@DynamoDBAttribute
	public String getBidderAdd() {
		return bidderAdd;
	}
	public void setBidderAdd(String bidderAdd) {
		this.bidderAdd = bidderAdd;
	}
	@DynamoDBAttribute
	public String getBidderPincode() {
		return bidderPincode;
	}
	public void setBidderPincode(String bidderPincode) {
		this.bidderPincode = bidderPincode;
	}
	@DynamoDBAttribute
	public String getBidderState() {
		return bidderState;
	}
	public void setBidderState(String bidderState) {
		this.bidderState = bidderState;
	}
	
	/*
	 * public BidingDO(String name, String bidderName, double bidAmount) { super();
	 * this.name = name; this.bidderName = bidderName; this.bidAmount = bidAmount; }
	 * public BidingDO() { super(); }
	 */
	
	
	
}
