package com.command.service.vo;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "product_info")
public class ProductInfo {
	private long id;
	private String name;
	private String short_desc;
	private String detailed_desc;
	private String category;
	private double price;
	private Date bidEndDate;
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public long getId() {
		return id;
	}
	@DynamoDBAttribute
	public String getName() {
		return name;
	}
	@DynamoDBAttribute
	public String getShort_desc() {
		return short_desc;
	}
	@DynamoDBAttribute
	public String getDetailed_desc() {
		return detailed_desc;
	}
	@DynamoDBAttribute
	public String getCategory() {
		return category;
	}
	@DynamoDBAttribute
	public double getPrice() {
		return price;
	}
	@DynamoDBAttribute
	public Date getBidEndDate() {
		return bidEndDate;
	}
	public void setId(long id) {
		this.id = id;
	}
	public void setName(String name) {
		this.name = name;
	}
	public void setShort_desc(String short_desc) {
		this.short_desc = short_desc;
	}
	public void setDetailed_desc(String detailed_desc) {
		this.detailed_desc = detailed_desc;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	public void setBidEndDate(Date bidEndDate) {
		this.bidEndDate = bidEndDate;
	}
	
	
}
