package com.query.service.vo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "bid")
public class BidingDO {

	private int id;
	private String name;
	private String bidderName;
	private double bidAmount;
	
	@DynamoDBAutoGeneratedKey
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	@DynamoDBHashKey
	@DynamoDBAttribute
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@DynamoDBAttribute
	public String getBidderName() {
		return bidderName;
	}
	public void setBidderName(String bidderName) {
		this.bidderName = bidderName;
	}
	@DynamoDBAttribute
	public double getBidAmount() {
		return bidAmount;
	}
	public void setBidAmount(double bidAmount) {
		this.bidAmount = bidAmount;
	}
	public BidingDO(String name, String bidderName, double bidAmount) {
		super();
		this.name = name;
		this.bidderName = bidderName;
		this.bidAmount = bidAmount;
	}
	/*
	 * public BidingDO() { super(); }
	 */
	
	
	
}
